### PR TITLE
Fix use correct m3 color for input text in an EditText element

### PR DESCRIPTION
**Pull request by AndyScherzinger**
...as raised via https://github.com/nextcloud/android-common/commit/50e641ee33a834ab89315ea86bf6cb2bb0f40b58#r146806120

impacting https://github.com/stefan-niedermann/nextcloud-deck/pull/1675

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
cc @Ornanovitch

**Comment by Ornanovitch** [comment]
Thanks a lot for having confirm this!

I detected a few other affected lines, all in `AndroidViewThemeUtils.kt` (all other files in the commit are OK).

Do not hesitate if you prefer me to raise another PR :)

https://github.com/nextcloud/android-common/blob/c7a8bf705b62c2ed9fda4a5c9627d248e89e54c2/ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt#L82

https://github.com/nextcloud/android-common/blob/c7a8bf705b62c2ed9fda4a5c9627d248e89e54c2/ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt#L151

https://github.com/nextcloud/android-common/blob/c7a8bf705b62c2ed9fda4a5c9627d248e89e54c2/ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt#L269

https://github.com/nextcloud/android-common/blob/c7a8bf705b62c2ed9fda4a5c9627d248e89e54c2/ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt#L273

https://github.com/nextcloud/android-common/blob/c7a8bf705b62c2ed9fda4a5c9627d248e89e54c2/ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt#L455

https://github.com/nextcloud/android-common/blob/c7a8bf705b62c2ed9fda4a5c9627d248e89e54c2/ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt#L512

**Comment by AndyScherzinger** [comment]
@Ornanovitch good catch! 👍 Fixed them to and merged to master. Could you give either `main-SNAPSHOT` or `9a66c0f56c` as a version string on the common-lib dependency and tell me if it is working for you, than I can trigger a proper stable release later.

**Comment by Ornanovitch** [comment]
Thanks a lot!

I will test this ASAP, probably this weekend and I'll let you know :)

**Comment by AndyScherzinger** [comment]
Sounds great 👍 
I haven't had the time to test but also checked all lines of code you mentioned and checked them against the Material3 specification and all your findings matched, so they should all be fine now.

**Comment by Ornanovitch** [comment]
Sad news..! While the fixes we made seem perfectly necessary, it doesn't change anything on the Deck side. We will need to investigate further, because probably something else is wrong, but maybe not in the Android-common library. Let's move on..!

**Pull request closed without merging**
