### PR TITLE
feat(ui): Theme BottomSheetDragHandleView

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Refs: https://m3.material.io/components/bottom-sheets/specs

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
fine by me, or we go straight for https://github.com/nextcloud/android-common/pull/208/commits/a89c4bd9834c113ebe46520e4528bcc2dd909a2a and the PR #208 while with the new Google implementation there is no fixed/stored values anymore but they are continuously calculated upon requesting them. However Scheme is deprecated with DynamicScheme. So we could either merge it and later add a "caching" object inbetween. OR are fine with the dynamic calculation.

What do you think @stefan-niedermann  ?

**Review by AndyScherzinger — APPROVED** [review]

**Comment by stefan-niedermann** [comment]
I don't need it urgently, so I think I can rebase it after `DynamicScheme` has been merged :slightly_smiling_face:

**Comment by AndyScherzinger** [comment]
@stefan-niedermann what is your point of view on merging dynamicScheme? I will calculate any color on each access of the color, so far I didn't see any performance impact from an experience perspective on the talk client so I'd be fine with merging and release that version as-is and in case performance becomes an issue add a way to cache the calculated colors, not sure though that is possible/easy given the dynamicScheme implementation of Google.

**Comment by AndyScherzinger** [comment]
Released with 0.15.0 @stefan-niedermann, have fun 🚀

**Pull request merged**
