### PR TITLE
Bump to SDK35

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Works with Files app ✔

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Lacks bump of the other sub projects still being on 34

**Comment by tobiasKaminsky** [comment]
> Lacks bump of the other sub projects still being on 34

I tested with integrating it in Files App and this works without problems:
>  implementation 'com.github.nextcloud:android-common:sdk35-SNAPSHOT'

So we can merge it.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger shall we do a release only with this change?

**Comment by AndyScherzinger** [comment]
with this one and the ktx lib bump, yes I'd say let's ship v0.24.0

**Comment by AndyScherzinger** [comment]
DONE via https://github.com/nextcloud/android-common/releases/tag/0.24.0

**Pull request merged**
